schema_version = "1.0.0"

id = "retargeteur"
version = "1.0.0"
name = "Retargeteur"
tagline = "Retarget actions between armatures"
maintainer = "Jackson Hayes"
type = "add-on"

blender_version_min = "4.5.0"
license = ["SPDX:LGPL-3.0-or-later"]
tags = ["Animation"]
